/*
 * File: app/store/storeOfertas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeOfertas', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.MyModel'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.MyModel',
        storeId: 'storeOfertas',
        proxy: {
            type: 'ajax',
            url: 'http://10.52.213.157/mp-ws/operaciones.php?operacion=sales_deals&lat=-33.27802477887706&lon=-66.31584810472997&range=50',
            reader: {
                type: 'json',
                rootProperty: 'deals'
            }
        }
    }
});