/*
 * File: app/store/storeOfertas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MPWallet.store.storeOfertas', {
    extend: 'Ext.data.Store',

    requires: [
        'MPWallet.model.MyModel'
    ],

    config: {
        data: [
            {
                id: 1,
                titulo: 'Speed',
                precio: '10.00',
                lugar: 'Vm',
                local: 'Garbarino'
            },
            {
                id: 2,
                titulo: 'Speed1',
                precio: '11.00',
                lugar: 'Vm1',
                local: 'Garbarino1'
            },
            {
                id: 3,
                titulo: 'Speed2',
                precio: '12.00',
                lugar: 'Vm2',
                local: 'Garbarino2'
            },
            {
                id: 4,
                titulo: 'Speed3',
                precio: '13.00',
                lugar: 'Vm3',
                local: 'Garbarino3'
            },
            {
                id: 5,
                titulo: 'Speed4',
                precio: '14.00',
                lugar: 'Vm4',
                local: 'Garbarino4'
            },
            {
                id: 6,
                titulo: 'Speed5',
                precio: '15.00',
                lugar: 'Vm5',
                local: 'Garbarino5'
            },
            {
                id: 7,
                titulo: 'Speed6',
                precio: '16.00',
                lugar: 'Vm6',
                local: 'Garbarino6'
            }
        ],
        model: 'MPWallet.model.MyModel',
        storeId: 'storeOfertas'
    }
});