/*
 * File: app/view/panelPrincipal.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MPWallet.view.panelPrincipal', {
    extend: 'Ext.Panel',

    config: {
        activeItem: 0,
        id: 'panelPrincipal',
        style: '',
        layout: {
            animation: 'scroll',
            type: 'card'
        },
        items: [
            {
                xtype: 'panel',
                id: 'panelLogin',
                items: [
                    {
                        xtype: 'image',
                        height: 86,
                        id: 'img',
                        src: 'app/resource/logo.png'
                    },
                    {
                        xtype: 'formpanel',
                        height: 448,
                        padding: '50 15 15 15',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'textUsuario',
                                label: 'Usuario'
                            },
                            {
                                xtype: 'passwordfield',
                                id: 'textPass',
                                label: 'Contraseña'
                            },
                            {
                                xtype: 'button',
                                id: 'btnEntrar',
                                itemId: 'mybutton',
                                margin: '20 auto 0 auto',
                                padding: '',
                                ui: 'action',
                                width: 200,
                                text: 'Entrar'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'panelMenu',
                items: [
                    {
                        xtype: 'tabpanel',
                        centered: false,
                        height: '100%',
                        id: 'panelPagar',
                        style: '',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Pagar',
                                centered: false,
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'formpanel',
                                        height: '100%',
                                        padding: '50 0 0 0',
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Ingresar Código',
                                                margin: '0 auto 0 auto',
                                                padding: '',
                                                width: 136
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'textCodigo',
                                                margin: '10 20 0 20',
                                                label: ''
                                            },
                                            {
                                                xtype: 'button',
                                                margin: '5% auto 0 auto',
                                                maxWidth: 150,
                                                ui: 'action',
                                                width: 150,
                                                text: 'Pagar'
                                            },
                                            {
                                                xtype: 'segmentedbutton',
                                                margin: '20 auto 0 auto',
                                                width: 224,
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        margin: '0 0 0 0',
                                                        maxWidth: 111,
                                                        padding: '',
                                                        width: 111,
                                                        text: 'Leer NFC'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        border: '',
                                                        itemId: 'mybutton63',
                                                        maxWidth: 111,
                                                        width: 111,
                                                        text: 'Leer QR'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: 'Ofertas',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'panel',
                                        height: '100%',
                                        items: [
                                            {
                                                xtype: 'label',
                                                docked: 'top',
                                                html: 'Ofertas cerca tuyo!'
                                            },
                                            {
                                                xtype: 'searchfield',
                                                docked: 'top',
                                                itemId: 'mysearchfield2',
                                                margin: 10,
                                                width: '80%',
                                                label: '',
                                                labelAlign: 'right',
                                                name: 'field'
                                            },
                                            {
                                                xtype: 'container',
                                                docked: 'bottom',
                                                height: '100%',
                                                ui: 'dark',
                                                width: '100%',
                                                layout: {
                                                    type: 'card'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'list',
                                                        height: '85%',
                                                        id: 'listOfertas',
                                                        itemId: 'mylist2',
                                                        margin: '0 0 100 0 ',
                                                        ui: 'round',
                                                        width: '100%',
                                                        scrollable: true,
                                                        itemTpl: [
                                                            '<div class="contact"><b>{titulo}<b><br>Precio: ${precio}<br> En {local} ({lugar})</div>'
                                                        ],
                                                        scrollToTopOnRefresh: false,
                                                        store: 'storeOfertas'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Buscar',
                                items: [
                                    {
                                        xtype: 'container',
                                        height: 47,
                                        padding: '0 50 0 0',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 50,
                                                ui: '',
                                                width: 60,
                                                src: 'app/resource/searchIcon.png'
                                            },
                                            {
                                                xtype: 'textfield',
                                                docked: 'left',
                                                height: 50,
                                                margin: 5,
                                                padding: '0 20 0 0',
                                                width: '80%',
                                                label: '',
                                                labelAlign: 'right',
                                                name: 'field'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        height: 377,
                                        width: '100%',
                                        itemTpl: [
                                            '<div>List Item {string}</div>'
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'panelOfertaDetalle',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton37',
                                ui: 'back',
                                text: 'Volver'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: 'Texto',
                        id: 'OD_labelTitulo'
                    },
                    {
                        xtype: 'spacer',
                        height: 25
                    },
                    {
                        xtype: 'label',
                        html: '$55.00',
                        id: 'OD_labelPrecio'
                    },
                    {
                        xtype: 'label',
                        html: 'Articulo nuevo',
                        id: 'OD_descArticulo'
                    },
                    {
                        xtype: 'spacer',
                        height: 29
                    },
                    {
                        xtype: 'label',
                        html: '12 Cuotas de 12.44',
                        id: 'OD_descripOferta'
                    },
                    {
                        xtype: 'label',
                        html: 'Medios de Pagos: Targeta Verde, Nevada, Mercado Pago, verde, lalal ., esta',
                        id: 'OD_pagos',
                        width: ''
                    },
                    {
                        xtype: 'image',
                        height: 201,
                        id: 'OD_img',
                        margin: '20 auto 0 auto',
                        maxWidth: 300,
                        minWidth: 300,
                        src: 'app/resource/searchIcon.png'
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '20 auto 20 auto',
                        width: 214,
                        items: [
                            {
                                xtype: 'button',
                                id: 'OD_btnReservar',
                                text: 'Reservar'
                            },
                            {
                                xtype: 'button',
                                id: 'OD_btnVerMapa',
                                text: 'Ver Mapa'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#btnEntrar'
            },
            {
                fn: 'onMybutton63Tap',
                event: 'tap',
                delegate: '#mybutton63'
            },
            {
                fn: 'onMysearchfield2Keyup',
                event: 'keyup',
                delegate: '#mysearchfield2'
            },
            {
                fn: 'onMylist2ItemTap',
                event: 'itemtap',
                delegate: '#listOfertas'
            },
            {
                fn: 'onMybutton37Tap',
                event: 'tap',
                delegate: '#mybutton37'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        var elemto = Ext.getCmp("panelPrincipal");
        elemto.setActiveItem(1);
    },

    onMybutton63Tap: function(button, e, eOpts) {
        new QrManager().startQr(function(lectura){
            Ext.getCmp('textCodigo').setText(lectura);
        });
    },

    onMysearchfield2Keyup: function(textfield, e, eOpts) {
        var filtro = textfield.getValue();
        var store = Ext.getStore("storeOfertas");

        store.filter( 'firstName', filtro, true,false);
        store.load();
    },

    onMylist2ItemTap: function(dataview, index, target, record, e, eOpts) {
        var evento = Ext.getCmp('panelPrincipal');


        var titulo = Ext.getCmp("OD_labelTitulo");
        titulo.setHtml(record.get("titulo"));

        var precio = Ext.getCmp("OD_labelPrecio");
        precio.setHtml(record.get("precio"));

        var descArticulo = Ext.getCmp("OD_descripOferta");
        descArticulo.setHtml(record.get("id") + " Articulo Nuevo");

        var pagos = Ext.getCmp("OD_pagos");
        pagos.setHtml(record.get("id") + " Pagos disponibles: Nevada, Mercado Pago");

        evento.setActiveItem(2);
    },

    onMybutton37Tap: function(button, e, eOpts) {
        Ext.getCmp("panelPrincipal").setActiveItem(1);
        Ext.getCmp("listOfertas").deselectAll();
    }

});