/*
 * File: app/view/panelPrincipal.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MPWallet.view.panelPrincipal', {
    extend: 'Ext.Panel',

    config: {
        activeItem: 0,
        id: 'panelPrincipal',
        layout: {
            animation: 'scroll',
            type: 'card'
        },
        items: [
            {
                xtype: 'panel',
                id: 'panelLogin',
                items: [
                    {
                        xtype: 'image',
                        height: 86,
                        id: 'img'
                    },
                    {
                        xtype: 'formpanel',
                        height: 448,
                        padding: '50 15 15 15',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'textUsuario',
                                label: 'Usuario'
                            },
                            {
                                xtype: 'passwordfield',
                                id: 'textPass',
                                label: 'Contraseña'
                            },
                            {
                                xtype: 'button',
                                id: 'btnEntrar',
                                itemId: 'mybutton',
                                margin: '20 auto 0 auto',
                                padding: '',
                                ui: 'action',
                                width: 200,
                                text: 'Entrar'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'panelMenu',
                items: [
                    {
                        xtype: 'tabpanel',
                        centered: false,
                        height: '100%',
                        id: 'panelPagar',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Pagar',
                                centered: false,
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'formpanel',
                                        height: '100%',
                                        padding: '50 0 0 0',
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Ingresar Código',
                                                margin: '0 auto 0 auto',
                                                padding: '',
                                                width: 136
                                            },
                                            {
                                                xtype: 'textfield',
                                                margin: '10 20 0 20',
                                                label: ''
                                            },
                                            {
                                                xtype: 'button',
                                                margin: '5% auto 0 auto',
                                                maxWidth: 150,
                                                ui: 'action',
                                                width: 150,
                                                text: 'Pagar'
                                            },
                                            {
                                                xtype: 'segmentedbutton',
                                                margin: '20 auto 0 auto',
                                                width: 224,
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        margin: '0 0 0 0',
                                                        maxWidth: 111,
                                                        padding: '',
                                                        width: 111,
                                                        text: 'Leer NFC'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        border: '',
                                                        maxWidth: 111,
                                                        width: 111,
                                                        text: 'Leer QR'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: 'Ofertas',
                                height: '100%',
                                items: [
                                    {
                                        xtype: 'panel',
                                        height: '100%',
                                        items: [
                                            {
                                                xtype: 'label',
                                                docked: 'top',
                                                html: 'Ofertas cerca tuyo!'
                                            },
                                            {
                                                xtype: 'searchfield',
                                                docked: 'top',
                                                itemId: 'mysearchfield2',
                                                width: 440,
                                                label: '',
                                                labelAlign: 'right',
                                                name: 'field'
                                            },
                                            {
                                                xtype: 'list',
                                                height: 1211,
                                                id: 'listOfertas',
                                                itemId: 'mylist2',
                                                ui: 'round',
                                                width: '100%',
                                                scrollable: 'vertical',
                                                itemTpl: [
                                                    '<div class="contact">Nombre: {firstName} <strong>{lastName}</strong></div>'
                                                ],
                                                store: 'storeOfertas'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Buscar',
                                items: [
                                    {
                                        xtype: 'container',
                                        height: 47,
                                        padding: '0 50 0 0',
                                        items: [
                                            {
                                                xtype: 'image',
                                                docked: 'left',
                                                height: 50,
                                                ui: '',
                                                width: 60,
                                                src: 'app/resource/searchIcon.png'
                                            },
                                            {
                                                xtype: 'textfield',
                                                docked: 'left',
                                                height: 50,
                                                margin: 5,
                                                padding: '0 20 0 0',
                                                width: '80%',
                                                label: '',
                                                labelAlign: 'right',
                                                name: 'field'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        height: 377,
                                        width: '100%',
                                        itemTpl: [
                                            '<div>List Item {string}</div>'
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'panelOfertaDetalle',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton37',
                                ui: 'back',
                                text: 'Volver'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#btnEntrar'
            },
            {
                fn: 'onMysearchfield2Keyup',
                event: 'keyup',
                delegate: '#mysearchfield2'
            },
            {
                fn: 'onMylist2ItemTap',
                event: 'itemtap',
                delegate: '#listOfertas'
            },
            {
                fn: 'onMybutton37Tap',
                event: 'tap',
                delegate: '#mybutton37'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        var elemto = Ext.getCmp("panelPrincipal");
        elemto.setActiveItem(1);
    },

    onMysearchfield2Keyup: function(textfield, e, eOpts) {
        var filtro = textfield.getValue();
        var store = Ext.getStore("storeOfertas");

        store.filter( 'firstName', filtro, true,false);
        store.load();
    },

    onMylist2ItemTap: function(dataview, index, target, record, e, eOpts) {
        var evento = Ext.getCmp('panelPrincipal');
        evento.setActiveItem(2);
    },

    onMybutton37Tap: function(button, e, eOpts) {
        Ext.getCmp("panelPrincipal").setActiveItem(1);
        Ext.getCmp("listOfertas").deselectAll();
    }

});